title: nineluj's website
theme: jekyll-theme-minimal
description: Julian Hirn's personal website
logo: https://avatars2.githubusercontent.com/u/11633602?s=460&u=b20079455bb8c09da23e4a60befb482c5e53e86b&v=4
